apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-mysql
spec:
  type: state.mysql
  version: v1
  metadata:
  - name: connectionString
    value: "root:Tai123456@tcp(localhost:3306)/?allowNativePasswords=true"

  